### ISSUE TITLE
site.posts.all() returns different post._ur'sl on two pages

### ISSUE THREAD

**Issue by thiagodebastos** [carrot/roots-dynamic-content#20]
## What
I am trying to apply a block, which includes a snippet for related posts, which simply lists other portfolio pieces for now.
The issue I am facing is that for some reason, Jade renders only one post in one page, but both in the other page. 

## How

``` jade
//- single-portfolio.jade
block content
	block creative-journey
	include related
```

``` jade
//- related.jade
each post in site.portfolio.all()
  li
    a(href= post._url)
      if post.relatedimageurl
        img(src= post.relatedimageurl)
      else
        img(src="http://lorempixel.com/325/250/abstract")
```
``` YAML
# dawnlister-therapy-centre.jade
# YAML front matter

date: 2014-01-15
title: Dawn Lister Therapy Centre.
description: Creative journey and case study for the Dawn Lister Therapy Centre website.
category: portfolio
tags: [website]
relatedimageurl: http://lorempixel.com/325/250/abstract/1
googlewebfonts: Lato|Open+Sans:400,700,800
_content: false

```

``` html
<!-- page1.html-->
<ul class="work-grid">
    <li><a href="/portfolio/dawn-lister-therapy-centre.html"><img src="http://lorempixel.com/325/250/abstract/1"></a></li>
</ul>

```

``` html
<!-- page2.html-->
<ul class="work-grid">
    <li><a href="/portfolio/dawn-lister-therapy-centre.html"><img src="http://lorempixel.com/325/250/abstract/1"></a></li>
    <li><a href="/portfolio/solid-nutrition-london.html"><img src="http://lorempixel.com/325/250/abstract/2"></a></li>
</ul>

```

## Why
Once this is working properly, I want to be able to list 3 related posts at the bottom of my page. I had this working [[1]](http://thiagodebastos.com/work/solid-nutrition-london/) [[2]](http://thiagodebastos.com/work/dawn-lister-therapy-centre/) in Jekyll and am in the process of converting everything into Roots because it rocks! 

### TLDR; What I Noticed
Rendered posts are not always in the same order. If I save a file while it is being watched, the contents of printed posts will swap around. I have confirmed this behaviour to exist in the output of content.json. I am not sure if this is related but I thought I would add the observation. If it is a bug, I am more than happy to move the issue where it belongs, if not here.

#### Extra Context
``` coffee
// app.coffee - irrelevant info such as locals have been ommited
module.exports =
  ignores: ['readme.md', '_templates/**/*', '**/_*', '**/*.sublime*',  '_includes/**/*', '.gitignore', '.editorconfig', 'ship.*conf']

  dump_dirs: [''] // fits my project structure

  extensions: [
    dynamic_content(write: 'content.json'),
    js_pipeline(files: ['assets/js/*.coffee', 'assets/js/*.js']),
    css_pipeline(files: 'assets/css/*.styl'),
    yaml()
  ]

  jade:
    pretty: true
    basedir: '/Users/Thiago/Code/thiagodebastos-roots/'
```
