### ISSUE TITLE
if no other content beyond front-matter, `obj.content` is incorrect

### ISSUE THREAD

**Issue by kylemac** [carrot/roots-dynamic-content#21]
given:
```yaml
# location1.jade
---
order: 1
name: 'Williamsburg'
address_1: '187 Bedford Avenue'
---
```

`site.locations[0].content` == `all of the front-matter in plain-text.`

this shouldn't be the case, since there is nothing beyond the front-matter, `obj.content` should be blank - but instead has the front-matter as a string.

the way to get around this is to add a blank string after the front-matter like so:
```yaml
# location1.jade
---
order: 1
name: 'Williamsburg'
address_1: '187 Bedford Avenue'
---
| 
```
